<#
  Create or overwrite a .env file at the repo root with sensible defaults.
  Host will default to the machine hostname so you can later swap it for a domain.

  Usage:
    scripts\create-env.ps1                 # create if missing (won't overwrite)
    scripts\create-env.ps1 -Force          # overwrite existing .env

  Optional overrides:
    scripts\create-env.ps1 -FrontendPort 5173 -BackendPort 4001 -HostName devbox
#>

[CmdletBinding()]
param(
  [switch]$Force,
  [int]$FrontendPort = 3000,
  [int]$BackendPort = 55000,
  [string]$HostName
)

try {
  $ErrorActionPreference = 'Stop'

  $root = Join-Path $PSScriptRoot '..' | Resolve-Path
  $envPath = Join-Path $root '.env'

  if (-not $HostName -or [string]::IsNullOrWhiteSpace($HostName)) {
    # Prefer DNS hostname; fall back to COMPUTERNAME
    try { $HostName = [System.Net.Dns]::GetHostName() } catch { }
    if (-not $HostName) { $HostName = $env:COMPUTERNAME }
  }

  if (Test-Path $envPath -PathType Leaf -ErrorAction SilentlyContinue) {
    if (-not $Force) {
      Write-Host "'.env' already exists at $envPath. Use -Force to overwrite."
      return
    }
  }

  $content = @"
# Generated by scripts/create-env.ps1
# Frontend dev server binding and port
PORT=$FrontendPort
HOST=0.0.0.0

# Public host used by scripts and UI links (set to machine hostname by default)
# You can change this later to a LAN IP or a domain (e.g., dev.gol.local).
HOST_IP=$HostName
GOL_HOST=$HostName
PUBLIC_HOST=$HostName

# Backend port (used by backend server, managers, and frontend default)
GOL_BACKEND_PORT=$BackendPort
REACT_APP_BACKEND_PORT=$BackendPort
"@

  $content | Out-File -FilePath $envPath -Encoding utf8 -NoNewline
  Write-Host "Wrote $envPath"
  Write-Host "- HOST/PORT for CRA bind: HOST=0.0.0.0 PORT=$FrontendPort"
  Write-Host "- Public host for links:  $HostName"
  Write-Host "- Backend port:           $BackendPort"
}
catch {
  Write-Error $_
  exit 1
}
