#!/usr/bin/env bash
set -euo pipefail

# Create or overwrite a .env file at the repo root with sensible defaults.
# Host will default to the machine HOSTNAME so you can later swap it for a domain.
# Usage:
#   scripts/create-env.sh            # create if missing (won't overwrite)
#   scripts/create-env.sh --force    # overwrite existing .env
# Optional environment overrides before running:
#   PORT=5173 GOL_BACKEND_PORT=4001 scripts/create-env.sh --force

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

FORCE=${1:-}

if [[ -f "$ENV_FILE" && "$FORCE" != "--force" ]]; then
  echo "'.env' already exists at $ENV_FILE. Use --force to overwrite."
  exit 0
fi

# Resolve host and ports
HOSTNAME_VAL="${HOSTNAME:-$(hostname)}"
FRONTEND_PORT="${PORT:-3000}"
# Prefer explicit backend vars if already in env, else default to 55000
BACKEND_PORT="${GOL_BACKEND_PORT:-${REACT_APP_BACKEND_PORT:-55000}}"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/create-env.sh
# Frontend dev server binding and port
PORT=$FRONTEND_PORT
HOST=0.0.0.0

# Public host used by scripts and UI links (set to machine hostname by default)
# You can change this later to a LAN IP or a domain (e.g., dev.gol.local).
HOST_IP=$HOSTNAME_VAL
GOL_HOST=$HOSTNAME_VAL
PUBLIC_HOST=$HOSTNAME_VAL

# Backend port (used by backend server, managers, and frontend default)
GOL_BACKEND_PORT=$BACKEND_PORT
REACT_APP_BACKEND_PORT=$BACKEND_PORT
EOF

echo "Wrote $ENV_FILE"
echo "- HOST/PORT for CRA bind: HOST=0.0.0.0 PORT=$FRONTEND_PORT"
echo "- Public host for links:  $HOSTNAME_VAL"
echo "- Backend port:           $BACKEND_PORT"
